version: "3"

silent: true
dotenv: [".env"]
output: prefixed
run: when_changed

tasks:
  onboard:
    cmds:
      - git config pull.rebase true
      - git config core.hooksPath $PWD/.hooks
      - git config commit.template $PWD/.gitmessagetpl

  lint:
    deps:
      - lint-bootstrap-script
      - lint-asdf-plugin
      - lint-asdf-plugin-fmt
      - lint-commit-msg
      - lint-pr-commit-msg

  lint-bootstrap-script:
    cmds:
      - echo "linting ./task"
      - shellcheck -s bash ./task

  lint-asdf-plugin:
    cmds:
      - echo "linting bin/*"
      - shellcheck -x -s bash -P lib/ bin/*

  lint-asdf-plugin-fmt:
    cmds:
      - echo "checking fmt ./task ./bin ./lib ./.hooks"
      - shfmt -d ./task ./bin ./lib ./.hooks

  lint-commit-msg:
    deps:
      - commitlint-install
    vars:
      GIT_EMPTY_SHA: "0000000000000000000000000000000000000000"
      BEFORE:
        sh: echo $GITHUB_CONTEXT | jq -r '.event.before'
      FORCED:
        sh: echo $GITHUB_CONTEXT | jq -r '.event.forced'
    cmds:
      - |
        if [ "${GITHUB_EVENT_NAME:-}" == "push" ]; then
          from="{{.BEFORE}}"

          if [ "{{.FORCED}}" == "true" ]; then
            echo "Commit was forced, checking only the latest commit from push instead of a range of commit messages."
            echo "When a commit is forced, the "before" field from the push event may point to a commit that doesn't exist."
            from="null"
          fi

          if [ "${from}" == "{{.GIT_EMPTY_SHA}}" ]; then
            echo "Checking only the latest commit from push instead of a range of commit messages, as this is the very first commit."
            from="null"
          fi

          if [ "${from}" == "null" ]; then
            from="${GITHUB_SHA}~1"
            echo "FROM=${from}"
            npx commitlint -V --from "${from}"
          else
            echo "FROM=${from}"
            echo "TO=${GITHUB_SHA}"
            npx commitlint -V --from "${from}" --to "${GITHUB_SHA}"
          fi
        fi

  lint-pr-commit-msg:
    deps:
      - commitlint-install
    vars:
      PR_TITLE:
        sh: echo $GITHUB_CONTEXT | jq -r '.event.pull_request.title'
      PR_NUMBER:
        sh: echo $GITHUB_CONTEXT | jq -r '.event.pull_request.number'
      PR_BODY:
        sh: echo $GITHUB_CONTEXT | jq -r '.event.pull_request.body'
    cmds:
      - |
        if [ "${GITHUB_EVENT_NAME:-}" == "pull_request" ]; then
          echo -e "{{.PR_TITLE}} (#{{.PR_NUMBER}})\n\n{{.PR_BODY}}" | npx commitlint -V
        fi

  fmt:
    cmds:
      - shfmt -l -w ./task ./bin ./lib ./.hooks

  test:
    vars:
      GIT_REPO: https://github.com/brad-jones/asdf-earthly.git
      TOOL_VERSION: '{{default "latest" .TOOL_VERSION}}'
    cmds:
      - |
        if [ ! -v CI ]; then
          echo ">>> Setting up local test env"
          curDir="$PWD"
          tmpDir="$(mktemp -d /tmp/asdfTest.XXXXXX)"
          cp -r "." "${tmpDir}"
          cd "${tmpDir}"
          git checkout -b testing
          git add ./bin ./lib
          git commit -n -m "chore: push new code to allow local testing"
          git push -u origin testing
          echo -e ">>> Local test env created, running tests\n\n"
        fi

        set +e
        asdf plugin test earthly "{{.GIT_REPO}}" \
          --asdf-tool-version "{{.TOOL_VERSION}}" \
          --asdf-plugin-gitref "${GITHUB_SHA:-testing}" \
          earthly --version
        status="$?"
        set -e;

        if [ ! -v CI ]; then
          echo -e "\n\n>>> Cleanup local test env"
          git push -d origin testing
          cd "${curDir}"
          rm -rf "${tmpDir}"
        fi

        exit "${status}"

  pre-commit:
    deps:
      - lint
      - test

  commit-msg:
    cmds:
      - task: commitlint
        vars:
          CLI_ARGS: -e -V

  commitlint-install:
    cmds:
      - if [ ! -d "$PWD/node_modules" ]; then npm ci; fi

  commitlint:
    deps:
      - commitlint-install
    cmds:
      - npx commitlint {{.CLI_ARGS}}

  release: echo "Hello World"
