on:
  push:
    branches:
      - master

env:
  CI: true
  GITHUB_CONTEXT: ${{ toJson(github) }}
  #JOB_CONTEXT: ${{ toJson(job) }}
  #MATRIX_CONTEXT: ${{ toJson(matrix) }}
  #RUNNER_CONTEXT: ${{ toJson(runner) }}
  #STEPS_CONTEXT: ${{ toJson(steps) }}
  #STRATEGY_CONTEXT: ${{ toJson(strategy) }}

jobs:
  lint:
    if: github.event.head_commit.committer.username != 'web-flow'
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - run: ./task lint

  test:
    if: github.event.head_commit.committer.username != 'web-flow'
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
      - run: ./task test

  release:
    needs: [lint, test]
    # see: https://github.com/actions/runner/issues/491
    if: |
      always() &&
      (needs.lint.result == 'success' || needs.lint.result == 'skipped') &&
      (needs.test.result == 'success' || needs.test.result == 'skipped')
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: ./task release
