on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  CI: true
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  lint:
    if: github.event.head_commit.committer.username != 'web-flow'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Cache ASDF Tools
        uses: actions/cache@v2.1.6
        with:
          key: ${{ runner.os }}-asdf-${{ hashFiles('task', '.tool-versions', '.asdf/.plugin-versions') }}
          restore-keys: ${{ runner.os }}-asdf-
          path: |
            ./.asdf/**/*
      - name: Cache Node Modules
        uses: actions/cache@v2.1.6
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
          path: |
            ~/.npm
      - run: ./task lint

  test:
    if: github.event.head_commit.committer.username != 'web-flow'
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
      - run: ./task test

  release:
    needs: [lint, test]
    # see: https://github.com/actions/runner/issues/491
    if: |
      always() &&
      (needs.lint.result == 'success' || needs.lint.result == 'skipped') &&
      (needs.test.result == 'success' || needs.test.result == 'skipped')
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: ./task release
